CREATE TABLE IF NOT EXISTS "users" (
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  user_id BIGINT NOT NULL UNIQUE,
  username TEXT NOT NULL UNIQUE,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS "users_states" (
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  user_id BIGINT NOT NULL,
  chat_id BIGINT NOT NULL,
  username TEXT NOT NULL,
  user_state TEXT DEFAULT "welcome_message" NOT NULL,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
  FOREIGN KEY(user_id) REFERENCES users(user_id)
);

CREATE TABLE IF NOT EXISTS "users_proposals" (
  id TEXT NOT NULL PRIMARY KEY UNIQUE,
  user_id BIGINT NOT NULL,
  proposal TEXT NOT NULL,
  isConfirmed TINYINT,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
  FOREIGN KEY(user_id) REFERENCES users(user_id)
);

CREATE TABLE IF NOT EXISTS "users_newsletter" (
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  user_id BIGINT NOT NULL,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
  FOREIGN KEY(user_id) REFERENCES users(user_id)
);

CREATE TABLE IF NOT EXISTS "users_bloqued_bot" (
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  user_id BIGINT NOT NULL,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
  FOREIGN KEY(user_id) REFERENCES users(user_id)
);
